apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: hypershift
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"hypershift-operator:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"operator\")].image"}]'
